function [ best, Population ] = REXstarJGG(Param)

%% Check Inputs
if isfield(Param.fitnessfun)
    error('Problem to be solved is not defined!');
end

C = {'par',...
    'output_intvl',...
    'vtr',...
    't_limit',...
    't_rextar',...
    'selection_type',...
    'out_transition',...
    'out_population',...
    'out_solution',...
    'n_generation',...
    'n_population',...
    'n_children',...
    'output_intvl',...
    'n_constraint',...
    'n_parent',...
    'Pf'};

tf = isfield(Param,C);



if length(Para)

if isfield(Param.fitnessfun)
    error('Problem to be solved is not defined!');
end


[ best, Population ] = RCGA_Main(Param,@JGG);
