#include "stddef.h"
#include "stdarg.h"
#include "math.h"
#include "CVODEmex25.h"
#include "BIOMD0000000051_url_mod_mex.h"
#include "mexsplineaddon.h"
#include "mexmathaddon.h"
#include "kineticformulas.h"

double time;

void model(double time_local, double *stateVector, double *DDTvector, ParamData *paramdataPtr, int DOflag, double *variableVector, double *reactionVector, double *gout, int *eventVector)
{
    double cpep,cglcex,cg6p,cpyr,cf6p,cg1p,cpg,cfdp,csed7p,cgap,ce4p,cxyl5p,crib5p,cdhap,cpgp,cpg3,cpg2,cribu5p;
    double vPTS_rmaxPTS,vPTS_KPTSa1,vPTS_KPTSa2,vPTS_KPTSa3,vPTS_nPTSg6p,vPTS_KPTSg6p,vPGI_rmaxPGI,vPGI_KPGIeq,vPGI_KPGIg6p,vPGI_KPGIf6p,vPGI_KPGIf6ppginh,vPGI_KPGIg6ppginh,vPGM_rmaxPGM,vPGM_KPGMeq,vPGM_KPGMg6p,vPGM_KPGMg1p,vG6PDH_rmaxG6PDH,vG6PDH_KG6PDHg6p,vG6PDH_KG6PDHnadphg6pinh,vG6PDH_KG6PDHnadp;
    double vG6PDH_KG6PDHnadphnadpinh,vPFK_rmaxPFK,vPFK_KPFKatps,vPFK_KPFKadpc,vPFK_KPFKf6ps,vPFK_KPFKpep,vPFK_KPFKadpb,vPFK_KPFKampb,vPFK_KPFKadpa,vPFK_KPFKampa,vPFK_LPFK,vPFK_nPFK,vTA_rmaxTA,vTA_KTAeq,vTKA_rmaxTKa,vTKA_KTKaeq,vTKB_rmaxTKb,vTKB_KTKbeq,vMURSyNTH_rmaxMurSynth,vALDO_rmaxALDO;
    double vALDO_kALDOeq,vALDO_kALDOfdp,vALDO_kALDOgap,vALDO_VALDOblf,vALDO_kALDOdhap,vALDO_kALDOgapinh,vGAPDH_rmaxGAPDH,vGAPDH_KGAPDHeq,vGAPDH_KGAPDHgap,vGAPDH_KGAPDHpgp,vGAPDH_KGAPDHnad,vGAPDH_KGAPDHnadh,vTIS_rmaxTIS,vTIS_kTISeq,vTIS_kTISdhap,vTIS_kTISgap,vTRPSYNTH_rmaxTrpSynth,vG3PDH_rmaxG3PDH,vG3PDH_KG3PDHdhap,vPGK_rmaxPGK;
    double vPGK_KPGKeq,vPGK_KPGKadp,vPGK_KPGKatp,vPGK_KPGKpgp,vPGK_KPGKpg3,vsersynth_rmaxSerSynth,vsersynth_KSerSynthpg3,vrpGluMu_rmaxPGluMu,vrpGluMu_KPGluMueq,vrpGluMu_KPGluMupg3,vrpGluMu_KPGluMupg2,vENO_rmaxENO,vENO_KENOeq,vENO_KENOpg2,vENO_KENOpep,vPK_rmaxPK,vPK_KPKpep,vPK_nPK,vPK_LPK,vPK_KPKatp;
    double vPK_KPKfdp,vPK_KPKamp,vPK_KPKadp,vpepCxylase_rmaxpepCxylase,vpepCxylase_KpepCxylasefdp,vpepCxylase_npepCxylasefdp,vpepCxylase_KpepCxylasepep,vSynth1_rmaxSynth1,vSynth1_KSynth1pep,vSynth2_rmaxSynth2,vSynth2_KSynth2pyr,vDAHPS_rmaxDAHPS,vDAHPS_nDAHPSe4p,vDAHPS_nDAHPSpep,vDAHPS_KDAHPSe4p,vDAHPS_KDAHPSpep,vPDH_rmaxPDH,vPDH_nPDH,vPDH_KPDHpyr,vMethSynth_rmaxMetSynth;
    double vPGDH_rmaxPGDH,vPGDH_KPGDHpg,vPGDH_KPGDHnadp,vPGDH_KPGDHnadphinh,vPGDH_KPGDHatpinh,vR5PI_rmaxR5PI,vR5PI_KR5PIeq,vRu5P_rmaxRu5P,vRu5P_KRu5Peq,vPPK_rmaxRPPK,vPPK_KRPPKrib5p,vG1PAT_rmaxG1PAT,vG1PAT_KG1PATfdp,vG1PAT_nG1PATfdp,vG1PAT_KG1PATatp,vG1PAT_KG1PATg1p,vG6P_mu,vf6P_mu,vfdP_mu,vGAP_mu;
    double vDHAP_mu,vPGP_mu,vPG3_mu,vpg2_mu,vPEP_mu,vRibu5p_mu,vRIB5P_mu,vXYL5P_mu,vSED7P_mu,vpyr_mu,vPG_mu,vE4P_mu,vGLP_mu,vEXTER_Dil,vEXTER_cfeed,extracellular,cytosol;
    double catp,cadp,camp,cnadph,cnadp,cnadh,cnad;
    double vPTS,vPGI,vPGM,vG6PDH,vPFK,vTA,vTKA,vTKB,vMURSyNTH,vALDO,vGAPDH,vTIS,vTRPSYNTH,vG3PDH,vPGK,vsersynth,vrpGluMu,vENO,vPK,vpepCxylase;
    double vSynth1,vSynth2,vDAHPS,vPDH,vMethSynth,vPGDH,vR5PI,vRu5P,vPPK,vG1PAT,vG6P,vf6P,vfdP,vGAP,vDHAP,vPGP,vPG3,vpg2,vPEP,vRibu5p;
    double vRIB5P,vXYL5P,vSED7P,vpyr,vPG,vE4P,vGLP,vEXTER;

    time = time_local;

    cpep = stateVector[0];
    cglcex = stateVector[1];
    cg6p = stateVector[2];
    cpyr = stateVector[3];
    cf6p = stateVector[4];
    cg1p = stateVector[5];
    cpg = stateVector[6];
    cfdp = stateVector[7];
    csed7p = stateVector[8];
    cgap = stateVector[9];
    ce4p = stateVector[10];
    cxyl5p = stateVector[11];
    crib5p = stateVector[12];
    cdhap = stateVector[13];
    cpgp = stateVector[14];
    cpg3 = stateVector[15];
    cpg2 = stateVector[16];
    cribu5p = stateVector[17];
    vPTS_rmaxPTS = paramdataPtr->parametervector[0]; /* 7829.78 */
    vPTS_KPTSa1 = paramdataPtr->parametervector[1]; /* 3082.3 */
    vPTS_KPTSa2 = paramdataPtr->parametervector[2]; /* 0.01 */
    vPTS_KPTSa3 = paramdataPtr->parametervector[3]; /* 245.3 */
    vPTS_nPTSg6p = paramdataPtr->parametervector[4]; /* 3.66 */
    vPTS_KPTSg6p = paramdataPtr->parametervector[5]; /* 2.15 */
    vPGI_rmaxPGI = paramdataPtr->parametervector[6]; /* 650.988 */
    vPGI_KPGIeq = paramdataPtr->parametervector[7]; /* 0.1725 */
    vPGI_KPGIg6p = paramdataPtr->parametervector[8]; /* 2.9 */
    vPGI_KPGIf6p = paramdataPtr->parametervector[9]; /* 0.266 */
    vPGI_KPGIf6ppginh = paramdataPtr->parametervector[10]; /* 0.2 */
    vPGI_KPGIg6ppginh = paramdataPtr->parametervector[11]; /* 0.2 */
    vPGM_rmaxPGM = paramdataPtr->parametervector[12]; /* 0.839824 */
    vPGM_KPGMeq = paramdataPtr->parametervector[13]; /* 0.196 */
    vPGM_KPGMg6p = paramdataPtr->parametervector[14]; /* 1.038 */
    vPGM_KPGMg1p = paramdataPtr->parametervector[15]; /* 0.0136 */
    vG6PDH_rmaxG6PDH = paramdataPtr->parametervector[16]; /* 1.3802 */
    vG6PDH_KG6PDHg6p = paramdataPtr->parametervector[17]; /* 14.4 */
    vG6PDH_KG6PDHnadphg6pinh = paramdataPtr->parametervector[18]; /* 6.43 */
    vG6PDH_KG6PDHnadp = paramdataPtr->parametervector[19]; /* 0.0246 */
    vG6PDH_KG6PDHnadphnadpinh = paramdataPtr->parametervector[20]; /* 0.01 */
    vPFK_rmaxPFK = paramdataPtr->parametervector[21]; /* 1840.58 */
    vPFK_KPFKatps = paramdataPtr->parametervector[22]; /* 0.123 */
    vPFK_KPFKadpc = paramdataPtr->parametervector[23]; /* 4.14 */
    vPFK_KPFKf6ps = paramdataPtr->parametervector[24]; /* 0.325 */
    vPFK_KPFKpep = paramdataPtr->parametervector[25]; /* 3.26 */
    vPFK_KPFKadpb = paramdataPtr->parametervector[26]; /* 3.89 */
    vPFK_KPFKampb = paramdataPtr->parametervector[27]; /* 3.2 */
    vPFK_KPFKadpa = paramdataPtr->parametervector[28]; /* 128 */
    vPFK_KPFKampa = paramdataPtr->parametervector[29]; /* 19.1 */
    vPFK_LPFK = paramdataPtr->parametervector[30]; /* 5.62907e+06 */
    vPFK_nPFK = paramdataPtr->parametervector[31]; /* 11.1 */
    vTA_rmaxTA = paramdataPtr->parametervector[32]; /* 10.8716 */
    vTA_KTAeq = paramdataPtr->parametervector[33]; /* 1.05 */
    vTKA_rmaxTKa = paramdataPtr->parametervector[34]; /* 9.47338 */
    vTKA_KTKaeq = paramdataPtr->parametervector[35]; /* 1.2 */
    vTKB_rmaxTKb = paramdataPtr->parametervector[36]; /* 86.5586 */
    vTKB_KTKbeq = paramdataPtr->parametervector[37]; /* 10 */
    vMURSyNTH_rmaxMurSynth = paramdataPtr->parametervector[38]; /* 0.00043711 */
    vALDO_rmaxALDO = paramdataPtr->parametervector[39]; /* 17.4146 */
    vALDO_kALDOeq = paramdataPtr->parametervector[40]; /* 0.144 */
    vALDO_kALDOfdp = paramdataPtr->parametervector[41]; /* 1.75 */
    vALDO_kALDOgap = paramdataPtr->parametervector[42]; /* 0.088 */
    vALDO_VALDOblf = paramdataPtr->parametervector[43]; /* 2 */
    vALDO_kALDOdhap = paramdataPtr->parametervector[44]; /* 0.088 */
    vALDO_kALDOgapinh = paramdataPtr->parametervector[45]; /* 0.6 */
    vGAPDH_rmaxGAPDH = paramdataPtr->parametervector[46]; /* 921.594 */
    vGAPDH_KGAPDHeq = paramdataPtr->parametervector[47]; /* 0.63 */
    vGAPDH_KGAPDHgap = paramdataPtr->parametervector[48]; /* 0.683 */
    vGAPDH_KGAPDHpgp = paramdataPtr->parametervector[49]; /* 1.04e-05 */
    vGAPDH_KGAPDHnad = paramdataPtr->parametervector[50]; /* 0.252 */
    vGAPDH_KGAPDHnadh = paramdataPtr->parametervector[51]; /* 1.09 */
    vTIS_rmaxTIS = paramdataPtr->parametervector[52]; /* 68.6747 */
    vTIS_kTISeq = paramdataPtr->parametervector[53]; /* 1.39 */
    vTIS_kTISdhap = paramdataPtr->parametervector[54]; /* 2.8 */
    vTIS_kTISgap = paramdataPtr->parametervector[55]; /* 0.3 */
    vTRPSYNTH_rmaxTrpSynth = paramdataPtr->parametervector[56]; /* 0.001037 */
    vG3PDH_rmaxG3PDH = paramdataPtr->parametervector[57]; /* 0.0116204 */
    vG3PDH_KG3PDHdhap = paramdataPtr->parametervector[58]; /* 1 */
    vPGK_rmaxPGK = paramdataPtr->parametervector[59]; /* 3021.77 */
    vPGK_KPGKeq = paramdataPtr->parametervector[60]; /* 1934.4 */
    vPGK_KPGKadp = paramdataPtr->parametervector[61]; /* 0.185 */
    vPGK_KPGKatp = paramdataPtr->parametervector[62]; /* 0.653 */
    vPGK_KPGKpgp = paramdataPtr->parametervector[63]; /* 0.0468 */
    vPGK_KPGKpg3 = paramdataPtr->parametervector[64]; /* 0.473 */
    vsersynth_rmaxSerSynth = paramdataPtr->parametervector[65]; /* 0.0257121 */
    vsersynth_KSerSynthpg3 = paramdataPtr->parametervector[66]; /* 1 */
    vrpGluMu_rmaxPGluMu = paramdataPtr->parametervector[67]; /* 89.0497 */
    vrpGluMu_KPGluMueq = paramdataPtr->parametervector[68]; /* 0.188 */
    vrpGluMu_KPGluMupg3 = paramdataPtr->parametervector[69]; /* 0.2 */
    vrpGluMu_KPGluMupg2 = paramdataPtr->parametervector[70]; /* 0.369 */
    vENO_rmaxENO = paramdataPtr->parametervector[71]; /* 330.448 */
    vENO_KENOeq = paramdataPtr->parametervector[72]; /* 6.73 */
    vENO_KENOpg2 = paramdataPtr->parametervector[73]; /* 0.1 */
    vENO_KENOpep = paramdataPtr->parametervector[74]; /* 0.135 */
    vPK_rmaxPK = paramdataPtr->parametervector[75]; /* 0.0611315 */
    vPK_KPKpep = paramdataPtr->parametervector[76]; /* 0.31 */
    vPK_nPK = paramdataPtr->parametervector[77]; /* 4 */
    vPK_LPK = paramdataPtr->parametervector[78]; /* 1000 */
    vPK_KPKatp = paramdataPtr->parametervector[79]; /* 22.5 */
    vPK_KPKfdp = paramdataPtr->parametervector[80]; /* 0.19 */
    vPK_KPKamp = paramdataPtr->parametervector[81]; /* 0.2 */
    vPK_KPKadp = paramdataPtr->parametervector[82]; /* 0.26 */
    vpepCxylase_rmaxpepCxylase = paramdataPtr->parametervector[83]; /* 0.107021 */
    vpepCxylase_KpepCxylasefdp = paramdataPtr->parametervector[84]; /* 0.7 */
    vpepCxylase_npepCxylasefdp = paramdataPtr->parametervector[85]; /* 4.21 */
    vpepCxylase_KpepCxylasepep = paramdataPtr->parametervector[86]; /* 4.07 */
    vSynth1_rmaxSynth1 = paramdataPtr->parametervector[87]; /* 0.019539 */
    vSynth1_KSynth1pep = paramdataPtr->parametervector[88]; /* 1 */
    vSynth2_rmaxSynth2 = paramdataPtr->parametervector[89]; /* 0.0736186 */
    vSynth2_KSynth2pyr = paramdataPtr->parametervector[90]; /* 1 */
    vDAHPS_rmaxDAHPS = paramdataPtr->parametervector[91]; /* 0.107953 */
    vDAHPS_nDAHPSe4p = paramdataPtr->parametervector[92]; /* 2.6 */
    vDAHPS_nDAHPSpep = paramdataPtr->parametervector[93]; /* 2.2 */
    vDAHPS_KDAHPSe4p = paramdataPtr->parametervector[94]; /* 0.035 */
    vDAHPS_KDAHPSpep = paramdataPtr->parametervector[95]; /* 0.0053 */
    vPDH_rmaxPDH = paramdataPtr->parametervector[96]; /* 6.05953 */
    vPDH_nPDH = paramdataPtr->parametervector[97]; /* 3.68 */
    vPDH_KPDHpyr = paramdataPtr->parametervector[98]; /* 1159 */
    vMethSynth_rmaxMetSynth = paramdataPtr->parametervector[99]; /* 0.0022627 */
    vPGDH_rmaxPGDH = paramdataPtr->parametervector[100]; /* 16.2324 */
    vPGDH_KPGDHpg = paramdataPtr->parametervector[101]; /* 37.5 */
    vPGDH_KPGDHnadp = paramdataPtr->parametervector[102]; /* 0.0506 */
    vPGDH_KPGDHnadphinh = paramdataPtr->parametervector[103]; /* 0.0138 */
    vPGDH_KPGDHatpinh = paramdataPtr->parametervector[104]; /* 208 */
    vR5PI_rmaxR5PI = paramdataPtr->parametervector[105]; /* 4.83841 */
    vR5PI_KR5PIeq = paramdataPtr->parametervector[106]; /* 4 */
    vRu5P_rmaxRu5P = paramdataPtr->parametervector[107]; /* 6.73903 */
    vRu5P_KRu5Peq = paramdataPtr->parametervector[108]; /* 1.4 */
    vPPK_rmaxRPPK = paramdataPtr->parametervector[109]; /* 0.0129005 */
    vPPK_KRPPKrib5p = paramdataPtr->parametervector[110]; /* 0.1 */
    vG1PAT_rmaxG1PAT = paramdataPtr->parametervector[111]; /* 0.00752546 */
    vG1PAT_KG1PATfdp = paramdataPtr->parametervector[112]; /* 0.119 */
    vG1PAT_nG1PATfdp = paramdataPtr->parametervector[113]; /* 1.2 */
    vG1PAT_KG1PATatp = paramdataPtr->parametervector[114]; /* 4.42 */
    vG1PAT_KG1PATg1p = paramdataPtr->parametervector[115]; /* 3.2 */
    vG6P_mu = paramdataPtr->parametervector[116]; /* 2.78e-05 */
    vf6P_mu = paramdataPtr->parametervector[117]; /* 2.78e-05 */
    vfdP_mu = paramdataPtr->parametervector[118]; /* 2.78e-05 */
    vGAP_mu = paramdataPtr->parametervector[119]; /* 2.78e-05 */
    vDHAP_mu = paramdataPtr->parametervector[120]; /* 2.78e-05 */
    vPGP_mu = paramdataPtr->parametervector[121]; /* 2.78e-05 */
    vPG3_mu = paramdataPtr->parametervector[122]; /* 2.78e-05 */
    vpg2_mu = paramdataPtr->parametervector[123]; /* 2.78e-05 */
    vPEP_mu = paramdataPtr->parametervector[124]; /* 2.78e-05 */
    vRibu5p_mu = paramdataPtr->parametervector[125]; /* 2.78e-05 */
    vRIB5P_mu = paramdataPtr->parametervector[126]; /* 2.78e-05 */
    vXYL5P_mu = paramdataPtr->parametervector[127]; /* 2.78e-05 */
    vSED7P_mu = paramdataPtr->parametervector[128]; /* 2.78e-05 */
    vpyr_mu = paramdataPtr->parametervector[129]; /* 2.78e-05 */
    vPG_mu = paramdataPtr->parametervector[130]; /* 2.78e-05 */
    vE4P_mu = paramdataPtr->parametervector[131]; /* 2.78e-05 */
    vGLP_mu = paramdataPtr->parametervector[132]; /* 2.78e-05 */
    vEXTER_Dil = paramdataPtr->parametervector[133]; /* 2.78e-05 */
    vEXTER_cfeed = paramdataPtr->parametervector[134]; /* 110.96 */
    extracellular = paramdataPtr->parametervector[135]; /* 1 */
    cytosol = paramdataPtr->parametervector[136]; /* 1 */
    catp = 4.27-4.163*(time/(0.657+1.43*time+0.0364*pow(time,2.0)));
    cadp = 0.582+1.73*pow(2.731,-0.15*time)*(0.12*time+0.000214*pow(time,3.0));
    camp = 0.123+7.25*(time/(7.25+1.47*time+0.17*pow(time,2.0)))+1.073/(1.29+8.05*time);
    cnadph = 0.062+0.332*pow(2.718,-0.464*time)*(0.0166*pow(time,1.58)+0.000166*pow(time,4.73)+0.1312*pow(10.0,-9.0)*pow(time,7.89)+0.1362*pow(10.0,-12.0)*pow(time,11.0)+0.1233*pow(10.0,-15.0)*pow(time,14.2));
    cnadp = 0.159-0.00554*(time/(2.8-0.271*time+0.01*pow(time,2.0)))+0.182/(4.82+0.526*time);
    cnadh = 0.0934+0.00111*pow(2.371,-0.123*time)*(0.844*time+0.104*pow(time,3.0));
    cnad = 1.314+1.314*pow(2.73,-0.0435*time-0.342)-(time+7.871)*(pow(2.73,-0.0218*time-0.171)/(8.481+time));
    vPTS = extracellular*vPTS_rmaxPTS*cglcex*(cpep/cpyr)/((vPTS_KPTSa1+vPTS_KPTSa2*(cpep/cpyr)+vPTS_KPTSa3*cglcex+cglcex*(cpep/cpyr))*(1.0+pow(cg6p,vPTS_nPTSg6p)/vPTS_KPTSg6p));
    vPGI = cytosol*vPGI_rmaxPGI*(cg6p-cf6p/vPGI_KPGIeq)/(vPGI_KPGIg6p*(1.0+cf6p/(vPGI_KPGIf6p*(1.0+cpg/vPGI_KPGIf6ppginh))+cpg/vPGI_KPGIg6ppginh)+cg6p);
    vPGM = cytosol*vPGM_rmaxPGM*(cg6p-cg1p/vPGM_KPGMeq)/(vPGM_KPGMg6p*(1.0+cg1p/vPGM_KPGMg1p)+cg6p);
    vG6PDH = cytosol*vG6PDH_rmaxG6PDH*cg6p*cnadp/((cg6p+vG6PDH_KG6PDHg6p)*(1.0+cnadph/vG6PDH_KG6PDHnadphg6pinh)*(vG6PDH_KG6PDHnadp*(1.0+cnadph/vG6PDH_KG6PDHnadphnadpinh)+cnadp));
    vPFK = cytosol*vPFK_rmaxPFK*catp*cf6p/((catp+vPFK_KPFKatps*(1.0+cadp/vPFK_KPFKadpc))*(cf6p+vPFK_KPFKf6ps*(1.0+cpep/vPFK_KPFKpep+cadp/vPFK_KPFKadpb+camp/vPFK_KPFKampb)/(1.0+cadp/vPFK_KPFKadpa+camp/vPFK_KPFKampa))*(1.0+vPFK_LPFK/pow(1.0+cf6p*(1.0+cadp/vPFK_KPFKadpa+camp/vPFK_KPFKampa)/(vPFK_KPFKf6ps*(1.0+cpep/vPFK_KPFKpep+cadp/vPFK_KPFKadpb+camp/vPFK_KPFKampb)),vPFK_nPFK)));
    vTA = cytosol*vTA_rmaxTA*(cgap*csed7p-ce4p*cf6p/vTA_KTAeq);
    vTKA = cytosol*vTKA_rmaxTKa*(crib5p*cxyl5p-csed7p*cgap/vTKA_KTKaeq);
    vTKB = cytosol*vTKB_rmaxTKb*(cxyl5p*ce4p-cf6p*cgap/vTKB_KTKbeq);
    vMURSyNTH = cytosol*vMURSyNTH_rmaxMurSynth;
    vALDO = cytosol*vALDO_rmaxALDO*(cfdp-cgap*cdhap/vALDO_kALDOeq)/(vALDO_kALDOfdp+cfdp+vALDO_kALDOgap*cdhap/(vALDO_kALDOeq*vALDO_VALDOblf)+vALDO_kALDOdhap*cgap/(vALDO_kALDOeq*vALDO_VALDOblf)+cfdp*cgap/vALDO_kALDOgapinh+cgap*cdhap/(vALDO_VALDOblf*vALDO_kALDOeq));
    vGAPDH = cytosol*vGAPDH_rmaxGAPDH*(cgap*cnad-cpgp*cnadh/vGAPDH_KGAPDHeq)/((vGAPDH_KGAPDHgap*(1.0+cpgp/vGAPDH_KGAPDHpgp)+cgap)*(vGAPDH_KGAPDHnad*(1.0+cnadh/vGAPDH_KGAPDHnadh)+cnad));
    vTIS = cytosol*vTIS_rmaxTIS*(cdhap-cgap/vTIS_kTISeq)/(vTIS_kTISdhap*(1.0+cgap/vTIS_kTISgap)+cdhap);
    vTRPSYNTH = cytosol*vTRPSYNTH_rmaxTrpSynth;
    vG3PDH = cytosol*vG3PDH_rmaxG3PDH*cdhap/(vG3PDH_KG3PDHdhap+cdhap);
    vPGK = cytosol*vPGK_rmaxPGK*(cadp*cpgp-catp*cpg3/vPGK_KPGKeq)/((vPGK_KPGKadp*(1.0+catp/vPGK_KPGKatp)+cadp)*(vPGK_KPGKpgp*(1.0+cpg3/vPGK_KPGKpg3)+cpgp));
    vsersynth = cytosol*vsersynth_rmaxSerSynth*cpg3/(vsersynth_KSerSynthpg3+cpg3);
    vrpGluMu = cytosol*vrpGluMu_rmaxPGluMu*(cpg3-cpg2/vrpGluMu_KPGluMueq)/(vrpGluMu_KPGluMupg3*(1.0+cpg2/vrpGluMu_KPGluMupg2)+cpg3);
    vENO = cytosol*vENO_rmaxENO*(cpg2-cpep/vENO_KENOeq)/(vENO_KENOpg2*(1.0+cpep/vENO_KENOpep)+cpg2);
    vPK = cytosol*vPK_rmaxPK*cpep*pow(cpep/vPK_KPKpep+1.0,vPK_nPK-1.0)*cadp/(vPK_KPKpep*(vPK_LPK*pow((1.0+catp/vPK_KPKatp)/(cfdp/vPK_KPKfdp+camp/vPK_KPKamp+1.0),vPK_nPK)+pow(cpep/vPK_KPKpep+1.0,vPK_nPK))*(cadp+vPK_KPKadp));
    vpepCxylase = cytosol*vpepCxylase_rmaxpepCxylase*cpep*(1.0+pow(cfdp/vpepCxylase_KpepCxylasefdp,vpepCxylase_npepCxylasefdp))/(vpepCxylase_KpepCxylasepep+cpep);
    vSynth1 = cytosol*vSynth1_rmaxSynth1*cpep/(vSynth1_KSynth1pep+cpep);
    vSynth2 = cytosol*vSynth2_rmaxSynth2*cpyr/(vSynth2_KSynth2pyr+cpyr);
    vDAHPS = cytosol*vDAHPS_rmaxDAHPS*pow(ce4p,vDAHPS_nDAHPSe4p)*pow(cpep,vDAHPS_nDAHPSpep)/((vDAHPS_KDAHPSe4p+pow(ce4p,vDAHPS_nDAHPSe4p))*(vDAHPS_KDAHPSpep+pow(cpep,vDAHPS_nDAHPSpep)));
    vPDH = cytosol*vPDH_rmaxPDH*pow(cpyr,vPDH_nPDH)/(vPDH_KPDHpyr+pow(cpyr,vPDH_nPDH));
    vMethSynth = cytosol*vMethSynth_rmaxMetSynth;
    vPGDH = cytosol*vPGDH_rmaxPGDH*cpg*cnadp/((cpg+vPGDH_KPGDHpg)*(cnadp+vPGDH_KPGDHnadp*(1.0+cnadph/vPGDH_KPGDHnadphinh)*(1.0+catp/vPGDH_KPGDHatpinh)));
    vR5PI = cytosol*vR5PI_rmaxR5PI*(cribu5p-crib5p/vR5PI_KR5PIeq);
    vRu5P = cytosol*vRu5P_rmaxRu5P*(cribu5p-cxyl5p/vRu5P_KRu5Peq);
    vPPK = cytosol*vPPK_rmaxRPPK*crib5p/(vPPK_KRPPKrib5p+crib5p);
    vG1PAT = cytosol*vG1PAT_rmaxG1PAT*cg1p*catp*(1.0+pow(cfdp/vG1PAT_KG1PATfdp,vG1PAT_nG1PATfdp))/((vG1PAT_KG1PATatp+catp)*(vG1PAT_KG1PATg1p+cg1p));
    vG6P = cytosol*vG6P_mu*cg6p;
    vf6P = cytosol*vf6P_mu*cf6p;
    vfdP = cytosol*vfdP_mu*cfdp;
    vGAP = cytosol*vGAP_mu*cgap;
    vDHAP = cytosol*vDHAP_mu*cdhap;
    vPGP = cytosol*vPGP_mu*cpgp;
    vPG3 = cytosol*vPG3_mu*cpg3;
    vpg2 = cytosol*vpg2_mu*cpg2;
    vPEP = cytosol*vPEP_mu*cpep;
    vRibu5p = cytosol*vRibu5p_mu*cribu5p;
    vRIB5P = cytosol*vRIB5P_mu*crib5p;
    vXYL5P = cytosol*vXYL5P_mu*cxyl5p;
    vSED7P = cytosol*vSED7P_mu*csed7p;
    vpyr = cytosol*vpyr_mu*cpyr;
    vPG = cytosol*vPG_mu*cpg;
    vE4P = cytosol*vE4P_mu*ce4p;
    vGLP = cytosol*vGLP_mu*cg1p;
    vEXTER = extracellular*vEXTER_Dil*(vEXTER_cfeed-cglcex);
    if (DOflag == DOFLAG_DDT) {
    	DDTvector[0] = (-65.0*vPTS+vENO-vPK-vpepCxylase-vSynth1-vDAHPS-vPEP)/cytosol;
    	DDTvector[1] = (-vPTS+vEXTER)/extracellular;
    	DDTvector[2] = (+65.0*vPTS-vPGI-vPGM-vG6PDH-vG6P)/cytosol;
    	DDTvector[3] = (+65.0*vPTS+vTRPSYNTH+vPK-vSynth2-vPDH+vMethSynth-vpyr)/cytosol;
    	DDTvector[4] = (+vPGI-vPFK+vTA+vTKB-2.0*vMURSyNTH-vf6P)/cytosol;
    	DDTvector[5] = (+vPGM-vG1PAT-vGLP)/cytosol;
    	DDTvector[6] = (+vG6PDH-vPGDH-vPG)/cytosol;
    	DDTvector[7] = (+vPFK-vALDO-vfdP)/cytosol;
    	DDTvector[8] = (-vTA+vTKA-vSED7P)/cytosol;
    	DDTvector[9] = (-vTA+vTKA+vTKB+vALDO-vGAPDH+vTIS+vTRPSYNTH-vGAP)/cytosol;
    	DDTvector[10] = (+vTA-vTKB-vDAHPS-vE4P)/cytosol;
    	DDTvector[11] = (-vTKA-vTKB+vRu5P-vXYL5P)/cytosol;
    	DDTvector[12] = (-vTKA+vR5PI-vPPK-vRIB5P)/cytosol;
    	DDTvector[13] = (+vALDO-vTIS-vG3PDH-vDHAP)/cytosol;
    	DDTvector[14] = (+vGAPDH-vPGK-vPGP)/cytosol;
    	DDTvector[15] = (+vPGK-vsersynth-vrpGluMu-vPG3)/cytosol;
    	DDTvector[16] = (+vrpGluMu-vENO-vpg2)/cytosol;
    	DDTvector[17] = (+vPGDH-vR5PI-vRu5P-vRibu5p)/cytosol;
    } else if (DOflag == DOFLAG_VARREAC) {
        variableVector[0] = catp;
        variableVector[1] = cadp;
        variableVector[2] = camp;
        variableVector[3] = cnadph;
        variableVector[4] = cnadp;
        variableVector[5] = cnadh;
        variableVector[6] = cnad;
        reactionVector[0] = vPTS;
        reactionVector[1] = vPGI;
        reactionVector[2] = vPGM;
        reactionVector[3] = vG6PDH;
        reactionVector[4] = vPFK;
        reactionVector[5] = vTA;
        reactionVector[6] = vTKA;
        reactionVector[7] = vTKB;
        reactionVector[8] = vMURSyNTH;
        reactionVector[9] = vALDO;
        reactionVector[10] = vGAPDH;
        reactionVector[11] = vTIS;
        reactionVector[12] = vTRPSYNTH;
        reactionVector[13] = vG3PDH;
        reactionVector[14] = vPGK;
        reactionVector[15] = vsersynth;
        reactionVector[16] = vrpGluMu;
        reactionVector[17] = vENO;
        reactionVector[18] = vPK;
        reactionVector[19] = vpepCxylase;
        reactionVector[20] = vSynth1;
        reactionVector[21] = vSynth2;
        reactionVector[22] = vDAHPS;
        reactionVector[23] = vPDH;
        reactionVector[24] = vMethSynth;
        reactionVector[25] = vPGDH;
        reactionVector[26] = vR5PI;
        reactionVector[27] = vRu5P;
        reactionVector[28] = vPPK;
        reactionVector[29] = vG1PAT;
        reactionVector[30] = vG6P;
        reactionVector[31] = vf6P;
        reactionVector[32] = vfdP;
        reactionVector[33] = vGAP;
        reactionVector[34] = vDHAP;
        reactionVector[35] = vPGP;
        reactionVector[36] = vPG3;
        reactionVector[37] = vpg2;
        reactionVector[38] = vPEP;
        reactionVector[39] = vRibu5p;
        reactionVector[40] = vRIB5P;
        reactionVector[41] = vXYL5P;
        reactionVector[42] = vSED7P;
        reactionVector[43] = vpyr;
        reactionVector[44] = vPG;
        reactionVector[45] = vE4P;
        reactionVector[46] = vGLP;
        reactionVector[47] = vEXTER;
    } else if (DOflag == DOFLAG_EVENTS) {
    } else if (DOflag == DOFLAG_EVENTASSIGN) {
    }
}


/* Function for initial condition calculation */
void calc_ic_model(double *icVector, ParamData *paramdataPtr)
{
    double cpep,cglcex,cg6p,cpyr,cf6p,cg1p,cpg,cfdp,csed7p,cgap,ce4p,cxyl5p,crib5p,cdhap,cpgp,cpg3,cpg2,cribu5p;
    double vPTS_rmaxPTS,vPTS_KPTSa1,vPTS_KPTSa2,vPTS_KPTSa3,vPTS_nPTSg6p,vPTS_KPTSg6p,vPGI_rmaxPGI,vPGI_KPGIeq,vPGI_KPGIg6p,vPGI_KPGIf6p,vPGI_KPGIf6ppginh,vPGI_KPGIg6ppginh,vPGM_rmaxPGM,vPGM_KPGMeq,vPGM_KPGMg6p,vPGM_KPGMg1p,vG6PDH_rmaxG6PDH,vG6PDH_KG6PDHg6p,vG6PDH_KG6PDHnadphg6pinh,vG6PDH_KG6PDHnadp;
    double vG6PDH_KG6PDHnadphnadpinh,vPFK_rmaxPFK,vPFK_KPFKatps,vPFK_KPFKadpc,vPFK_KPFKf6ps,vPFK_KPFKpep,vPFK_KPFKadpb,vPFK_KPFKampb,vPFK_KPFKadpa,vPFK_KPFKampa,vPFK_LPFK,vPFK_nPFK,vTA_rmaxTA,vTA_KTAeq,vTKA_rmaxTKa,vTKA_KTKaeq,vTKB_rmaxTKb,vTKB_KTKbeq,vMURSyNTH_rmaxMurSynth,vALDO_rmaxALDO;
    double vALDO_kALDOeq,vALDO_kALDOfdp,vALDO_kALDOgap,vALDO_VALDOblf,vALDO_kALDOdhap,vALDO_kALDOgapinh,vGAPDH_rmaxGAPDH,vGAPDH_KGAPDHeq,vGAPDH_KGAPDHgap,vGAPDH_KGAPDHpgp,vGAPDH_KGAPDHnad,vGAPDH_KGAPDHnadh,vTIS_rmaxTIS,vTIS_kTISeq,vTIS_kTISdhap,vTIS_kTISgap,vTRPSYNTH_rmaxTrpSynth,vG3PDH_rmaxG3PDH,vG3PDH_KG3PDHdhap,vPGK_rmaxPGK;
    double vPGK_KPGKeq,vPGK_KPGKadp,vPGK_KPGKatp,vPGK_KPGKpgp,vPGK_KPGKpg3,vsersynth_rmaxSerSynth,vsersynth_KSerSynthpg3,vrpGluMu_rmaxPGluMu,vrpGluMu_KPGluMueq,vrpGluMu_KPGluMupg3,vrpGluMu_KPGluMupg2,vENO_rmaxENO,vENO_KENOeq,vENO_KENOpg2,vENO_KENOpep,vPK_rmaxPK,vPK_KPKpep,vPK_nPK,vPK_LPK,vPK_KPKatp;
    double vPK_KPKfdp,vPK_KPKamp,vPK_KPKadp,vpepCxylase_rmaxpepCxylase,vpepCxylase_KpepCxylasefdp,vpepCxylase_npepCxylasefdp,vpepCxylase_KpepCxylasepep,vSynth1_rmaxSynth1,vSynth1_KSynth1pep,vSynth2_rmaxSynth2,vSynth2_KSynth2pyr,vDAHPS_rmaxDAHPS,vDAHPS_nDAHPSe4p,vDAHPS_nDAHPSpep,vDAHPS_KDAHPSe4p,vDAHPS_KDAHPSpep,vPDH_rmaxPDH,vPDH_nPDH,vPDH_KPDHpyr,vMethSynth_rmaxMetSynth;
    double vPGDH_rmaxPGDH,vPGDH_KPGDHpg,vPGDH_KPGDHnadp,vPGDH_KPGDHnadphinh,vPGDH_KPGDHatpinh,vR5PI_rmaxR5PI,vR5PI_KR5PIeq,vRu5P_rmaxRu5P,vRu5P_KRu5Peq,vPPK_rmaxRPPK,vPPK_KRPPKrib5p,vG1PAT_rmaxG1PAT,vG1PAT_KG1PATfdp,vG1PAT_nG1PATfdp,vG1PAT_KG1PATatp,vG1PAT_KG1PATg1p,vG6P_mu,vf6P_mu,vfdP_mu,vGAP_mu;
    double vDHAP_mu,vPGP_mu,vPG3_mu,vpg2_mu,vPEP_mu,vRibu5p_mu,vRIB5P_mu,vXYL5P_mu,vSED7P_mu,vpyr_mu,vPG_mu,vE4P_mu,vGLP_mu,vEXTER_Dil,vEXTER_cfeed,extracellular,cytosol;
    double catp,cadp,camp,cnadph,cnadp,cnadh,cnad;
    vPTS_rmaxPTS = paramdataPtr->parametervector[0]; /* 7829.78 */
    vPTS_KPTSa1 = paramdataPtr->parametervector[1]; /* 3082.3 */
    vPTS_KPTSa2 = paramdataPtr->parametervector[2]; /* 0.01 */
    vPTS_KPTSa3 = paramdataPtr->parametervector[3]; /* 245.3 */
    vPTS_nPTSg6p = paramdataPtr->parametervector[4]; /* 3.66 */
    vPTS_KPTSg6p = paramdataPtr->parametervector[5]; /* 2.15 */
    vPGI_rmaxPGI = paramdataPtr->parametervector[6]; /* 650.988 */
    vPGI_KPGIeq = paramdataPtr->parametervector[7]; /* 0.1725 */
    vPGI_KPGIg6p = paramdataPtr->parametervector[8]; /* 2.9 */
    vPGI_KPGIf6p = paramdataPtr->parametervector[9]; /* 0.266 */
    vPGI_KPGIf6ppginh = paramdataPtr->parametervector[10]; /* 0.2 */
    vPGI_KPGIg6ppginh = paramdataPtr->parametervector[11]; /* 0.2 */
    vPGM_rmaxPGM = paramdataPtr->parametervector[12]; /* 0.839824 */
    vPGM_KPGMeq = paramdataPtr->parametervector[13]; /* 0.196 */
    vPGM_KPGMg6p = paramdataPtr->parametervector[14]; /* 1.038 */
    vPGM_KPGMg1p = paramdataPtr->parametervector[15]; /* 0.0136 */
    vG6PDH_rmaxG6PDH = paramdataPtr->parametervector[16]; /* 1.3802 */
    vG6PDH_KG6PDHg6p = paramdataPtr->parametervector[17]; /* 14.4 */
    vG6PDH_KG6PDHnadphg6pinh = paramdataPtr->parametervector[18]; /* 6.43 */
    vG6PDH_KG6PDHnadp = paramdataPtr->parametervector[19]; /* 0.0246 */
    vG6PDH_KG6PDHnadphnadpinh = paramdataPtr->parametervector[20]; /* 0.01 */
    vPFK_rmaxPFK = paramdataPtr->parametervector[21]; /* 1840.58 */
    vPFK_KPFKatps = paramdataPtr->parametervector[22]; /* 0.123 */
    vPFK_KPFKadpc = paramdataPtr->parametervector[23]; /* 4.14 */
    vPFK_KPFKf6ps = paramdataPtr->parametervector[24]; /* 0.325 */
    vPFK_KPFKpep = paramdataPtr->parametervector[25]; /* 3.26 */
    vPFK_KPFKadpb = paramdataPtr->parametervector[26]; /* 3.89 */
    vPFK_KPFKampb = paramdataPtr->parametervector[27]; /* 3.2 */
    vPFK_KPFKadpa = paramdataPtr->parametervector[28]; /* 128 */
    vPFK_KPFKampa = paramdataPtr->parametervector[29]; /* 19.1 */
    vPFK_LPFK = paramdataPtr->parametervector[30]; /* 5.62907e+06 */
    vPFK_nPFK = paramdataPtr->parametervector[31]; /* 11.1 */
    vTA_rmaxTA = paramdataPtr->parametervector[32]; /* 10.8716 */
    vTA_KTAeq = paramdataPtr->parametervector[33]; /* 1.05 */
    vTKA_rmaxTKa = paramdataPtr->parametervector[34]; /* 9.47338 */
    vTKA_KTKaeq = paramdataPtr->parametervector[35]; /* 1.2 */
    vTKB_rmaxTKb = paramdataPtr->parametervector[36]; /* 86.5586 */
    vTKB_KTKbeq = paramdataPtr->parametervector[37]; /* 10 */
    vMURSyNTH_rmaxMurSynth = paramdataPtr->parametervector[38]; /* 0.00043711 */
    vALDO_rmaxALDO = paramdataPtr->parametervector[39]; /* 17.4146 */
    vALDO_kALDOeq = paramdataPtr->parametervector[40]; /* 0.144 */
    vALDO_kALDOfdp = paramdataPtr->parametervector[41]; /* 1.75 */
    vALDO_kALDOgap = paramdataPtr->parametervector[42]; /* 0.088 */
    vALDO_VALDOblf = paramdataPtr->parametervector[43]; /* 2 */
    vALDO_kALDOdhap = paramdataPtr->parametervector[44]; /* 0.088 */
    vALDO_kALDOgapinh = paramdataPtr->parametervector[45]; /* 0.6 */
    vGAPDH_rmaxGAPDH = paramdataPtr->parametervector[46]; /* 921.594 */
    vGAPDH_KGAPDHeq = paramdataPtr->parametervector[47]; /* 0.63 */
    vGAPDH_KGAPDHgap = paramdataPtr->parametervector[48]; /* 0.683 */
    vGAPDH_KGAPDHpgp = paramdataPtr->parametervector[49]; /* 1.04e-05 */
    vGAPDH_KGAPDHnad = paramdataPtr->parametervector[50]; /* 0.252 */
    vGAPDH_KGAPDHnadh = paramdataPtr->parametervector[51]; /* 1.09 */
    vTIS_rmaxTIS = paramdataPtr->parametervector[52]; /* 68.6747 */
    vTIS_kTISeq = paramdataPtr->parametervector[53]; /* 1.39 */
    vTIS_kTISdhap = paramdataPtr->parametervector[54]; /* 2.8 */
    vTIS_kTISgap = paramdataPtr->parametervector[55]; /* 0.3 */
    vTRPSYNTH_rmaxTrpSynth = paramdataPtr->parametervector[56]; /* 0.001037 */
    vG3PDH_rmaxG3PDH = paramdataPtr->parametervector[57]; /* 0.0116204 */
    vG3PDH_KG3PDHdhap = paramdataPtr->parametervector[58]; /* 1 */
    vPGK_rmaxPGK = paramdataPtr->parametervector[59]; /* 3021.77 */
    vPGK_KPGKeq = paramdataPtr->parametervector[60]; /* 1934.4 */
    vPGK_KPGKadp = paramdataPtr->parametervector[61]; /* 0.185 */
    vPGK_KPGKatp = paramdataPtr->parametervector[62]; /* 0.653 */
    vPGK_KPGKpgp = paramdataPtr->parametervector[63]; /* 0.0468 */
    vPGK_KPGKpg3 = paramdataPtr->parametervector[64]; /* 0.473 */
    vsersynth_rmaxSerSynth = paramdataPtr->parametervector[65]; /* 0.0257121 */
    vsersynth_KSerSynthpg3 = paramdataPtr->parametervector[66]; /* 1 */
    vrpGluMu_rmaxPGluMu = paramdataPtr->parametervector[67]; /* 89.0497 */
    vrpGluMu_KPGluMueq = paramdataPtr->parametervector[68]; /* 0.188 */
    vrpGluMu_KPGluMupg3 = paramdataPtr->parametervector[69]; /* 0.2 */
    vrpGluMu_KPGluMupg2 = paramdataPtr->parametervector[70]; /* 0.369 */
    vENO_rmaxENO = paramdataPtr->parametervector[71]; /* 330.448 */
    vENO_KENOeq = paramdataPtr->parametervector[72]; /* 6.73 */
    vENO_KENOpg2 = paramdataPtr->parametervector[73]; /* 0.1 */
    vENO_KENOpep = paramdataPtr->parametervector[74]; /* 0.135 */
    vPK_rmaxPK = paramdataPtr->parametervector[75]; /* 0.0611315 */
    vPK_KPKpep = paramdataPtr->parametervector[76]; /* 0.31 */
    vPK_nPK = paramdataPtr->parametervector[77]; /* 4 */
    vPK_LPK = paramdataPtr->parametervector[78]; /* 1000 */
    vPK_KPKatp = paramdataPtr->parametervector[79]; /* 22.5 */
    vPK_KPKfdp = paramdataPtr->parametervector[80]; /* 0.19 */
    vPK_KPKamp = paramdataPtr->parametervector[81]; /* 0.2 */
    vPK_KPKadp = paramdataPtr->parametervector[82]; /* 0.26 */
    vpepCxylase_rmaxpepCxylase = paramdataPtr->parametervector[83]; /* 0.107021 */
    vpepCxylase_KpepCxylasefdp = paramdataPtr->parametervector[84]; /* 0.7 */
    vpepCxylase_npepCxylasefdp = paramdataPtr->parametervector[85]; /* 4.21 */
    vpepCxylase_KpepCxylasepep = paramdataPtr->parametervector[86]; /* 4.07 */
    vSynth1_rmaxSynth1 = paramdataPtr->parametervector[87]; /* 0.019539 */
    vSynth1_KSynth1pep = paramdataPtr->parametervector[88]; /* 1 */
    vSynth2_rmaxSynth2 = paramdataPtr->parametervector[89]; /* 0.0736186 */
    vSynth2_KSynth2pyr = paramdataPtr->parametervector[90]; /* 1 */
    vDAHPS_rmaxDAHPS = paramdataPtr->parametervector[91]; /* 0.107953 */
    vDAHPS_nDAHPSe4p = paramdataPtr->parametervector[92]; /* 2.6 */
    vDAHPS_nDAHPSpep = paramdataPtr->parametervector[93]; /* 2.2 */
    vDAHPS_KDAHPSe4p = paramdataPtr->parametervector[94]; /* 0.035 */
    vDAHPS_KDAHPSpep = paramdataPtr->parametervector[95]; /* 0.0053 */
    vPDH_rmaxPDH = paramdataPtr->parametervector[96]; /* 6.05953 */
    vPDH_nPDH = paramdataPtr->parametervector[97]; /* 3.68 */
    vPDH_KPDHpyr = paramdataPtr->parametervector[98]; /* 1159 */
    vMethSynth_rmaxMetSynth = paramdataPtr->parametervector[99]; /* 0.0022627 */
    vPGDH_rmaxPGDH = paramdataPtr->parametervector[100]; /* 16.2324 */
    vPGDH_KPGDHpg = paramdataPtr->parametervector[101]; /* 37.5 */
    vPGDH_KPGDHnadp = paramdataPtr->parametervector[102]; /* 0.0506 */
    vPGDH_KPGDHnadphinh = paramdataPtr->parametervector[103]; /* 0.0138 */
    vPGDH_KPGDHatpinh = paramdataPtr->parametervector[104]; /* 208 */
    vR5PI_rmaxR5PI = paramdataPtr->parametervector[105]; /* 4.83841 */
    vR5PI_KR5PIeq = paramdataPtr->parametervector[106]; /* 4 */
    vRu5P_rmaxRu5P = paramdataPtr->parametervector[107]; /* 6.73903 */
    vRu5P_KRu5Peq = paramdataPtr->parametervector[108]; /* 1.4 */
    vPPK_rmaxRPPK = paramdataPtr->parametervector[109]; /* 0.0129005 */
    vPPK_KRPPKrib5p = paramdataPtr->parametervector[110]; /* 0.1 */
    vG1PAT_rmaxG1PAT = paramdataPtr->parametervector[111]; /* 0.00752546 */
    vG1PAT_KG1PATfdp = paramdataPtr->parametervector[112]; /* 0.119 */
    vG1PAT_nG1PATfdp = paramdataPtr->parametervector[113]; /* 1.2 */
    vG1PAT_KG1PATatp = paramdataPtr->parametervector[114]; /* 4.42 */
    vG1PAT_KG1PATg1p = paramdataPtr->parametervector[115]; /* 3.2 */
    vG6P_mu = paramdataPtr->parametervector[116]; /* 2.78e-05 */
    vf6P_mu = paramdataPtr->parametervector[117]; /* 2.78e-05 */
    vfdP_mu = paramdataPtr->parametervector[118]; /* 2.78e-05 */
    vGAP_mu = paramdataPtr->parametervector[119]; /* 2.78e-05 */
    vDHAP_mu = paramdataPtr->parametervector[120]; /* 2.78e-05 */
    vPGP_mu = paramdataPtr->parametervector[121]; /* 2.78e-05 */
    vPG3_mu = paramdataPtr->parametervector[122]; /* 2.78e-05 */
    vpg2_mu = paramdataPtr->parametervector[123]; /* 2.78e-05 */
    vPEP_mu = paramdataPtr->parametervector[124]; /* 2.78e-05 */
    vRibu5p_mu = paramdataPtr->parametervector[125]; /* 2.78e-05 */
    vRIB5P_mu = paramdataPtr->parametervector[126]; /* 2.78e-05 */
    vXYL5P_mu = paramdataPtr->parametervector[127]; /* 2.78e-05 */
    vSED7P_mu = paramdataPtr->parametervector[128]; /* 2.78e-05 */
    vpyr_mu = paramdataPtr->parametervector[129]; /* 2.78e-05 */
    vPG_mu = paramdataPtr->parametervector[130]; /* 2.78e-05 */
    vE4P_mu = paramdataPtr->parametervector[131]; /* 2.78e-05 */
    vGLP_mu = paramdataPtr->parametervector[132]; /* 2.78e-05 */
    vEXTER_Dil = paramdataPtr->parametervector[133]; /* 2.78e-05 */
    vEXTER_cfeed = paramdataPtr->parametervector[134]; /* 110.96 */
    extracellular = paramdataPtr->parametervector[135]; /* 1 */
    cytosol = paramdataPtr->parametervector[136]; /* 1 */
    catp = 4.27-4.163*(time/(0.657+1.43*time+0.0364*pow(time,2.0)));
    cadp = 0.582+1.73*pow(2.731,-0.15*time)*(0.12*time+0.000214*pow(time,3.0));
    camp = 0.123+7.25*(time/(7.25+1.47*time+0.17*pow(time,2.0)))+1.073/(1.29+8.05*time);
    cnadph = 0.062+0.332*pow(2.718,-0.464*time)*(0.0166*pow(time,1.58)+0.000166*pow(time,4.73)+0.1312*pow(10.0,-9.0)*pow(time,7.89)+0.1362*pow(10.0,-12.0)*pow(time,11.0)+0.1233*pow(10.0,-15.0)*pow(time,14.2));
    cnadp = 0.159-0.00554*(time/(2.8-0.271*time+0.01*pow(time,2.0)))+0.182/(4.82+0.526*time);
    cnadh = 0.0934+0.00111*pow(2.371,-0.123*time)*(0.844*time+0.104*pow(time,3.0));
    cnad = 1.314+1.314*pow(2.73,-0.0435*time-0.342)-(time+7.871)*(pow(2.73,-0.0218*time-0.171)/(8.481+time));
    cpep = 2.67;
    cglcex = 2.0;
    cg6p = 3.48;
    cpyr = 2.67;
    cf6p = 0.6;
    cg1p = 0.653;
    cpg = 0.808;
    cfdp = 0.272;
    csed7p = 0.276;
    cgap = 0.218;
    ce4p = 0.098;
    cxyl5p = 0.138;
    crib5p = 0.398;
    cdhap = 0.167;
    cpgp = 0.008;
    cpg3 = 2.13;
    cpg2 = 0.399;
    cribu5p = 0.111;
    icVector[0] = cpep;
    icVector[1] = cglcex;
    icVector[2] = cg6p;
    icVector[3] = cpyr;
    icVector[4] = cf6p;
    icVector[5] = cg1p;
    icVector[6] = cpg;
    icVector[7] = cfdp;
    icVector[8] = csed7p;
    icVector[9] = cgap;
    icVector[10] = ce4p;
    icVector[11] = cxyl5p;
    icVector[12] = crib5p;
    icVector[13] = cdhap;
    icVector[14] = cpgp;
    icVector[15] = cpg3;
    icVector[16] = cpg2;
    icVector[17] = cribu5p;
}

