function dydt = Model_Example_conciseOdefun(t, y)
% This function was generated by the function
% RCGAconvertIQMmodel2conciseOdefun from Model_Example_converted.xml.
% 22-Oct-2020
% 
% You can simulate the model coded in this function by the following codes.
% tspan = [0 10];
% y0(1) = 0.000000e+00;
% y0(2) = 0.000000e+00;
% [T, Y] = ode15s(@Model_Example_conciseOdefun,tspan,y0);
% plot(T, Y);
% xlabel('Time');
% ylabel('States');
% legend('X1','X2');


X1 = y(1);
X2 = y(2);

% === BEGIN NAME ===
% Model_Example
% === END NAME ===

% === BEGIN NOTES ===
% Simple metabolic pathway with two Michaelis-Menten rate equations.
% === END NOTES ===

% === BEGIN INITIAL CONDITION ===
X1_0 = 0.000000e+00;
X2_0 = 0.000000e+00;
% === END INITIAL CONDITION ===

% === BEGIN PARAMETERS ===
X0 = 1.000000e-01;
k1 = 1.000000e+00;
k2 = 1.000000e+00;
k3 = 1.000000e+00;
K2 = 1.000000e+00;
K3 = 1.000000e+00;
rootCompartment = 1.000000e+00;
% === END PARAMETERS ===

% === BEGIN VARIABLES ===
X12 = (X1/rootCompartment)+(X2/rootCompartment);
% === END VARIABLES ===

% === BEGIN REACTIONS ===
v1 = k1 * X0;
v2 = k2 * (X1/rootCompartment) / (K2 + (X1/rootCompartment));
v3 = k3 * (X2/rootCompartment) / (K3 + (X2/rootCompartment));
% === END REACTIONS ===

% === BEGIN BALANCE ===
X1_dot = +v1-v2;
X2_dot = +v2-v3;
% === END BALANCE ===

dydt = zeros(2,1);
dydt(1) = X1_dot;
dydt(2) = X2_dot;
